---
- name: Query AWS CLI version
  command: aws --version
  failed_when: false
  changed_when: false
  register: aws_cli_version

- name: Install AWS CLI
  when: aws_cli_version.rc != 0
  block:
    - name: Download and extract installer
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: true

    - name: Install AWS CLI
      command: /tmp/aws/install
      become: true

    - name: Cleanup installer
      file:
        path: /tmp/aws
        state: absent

    - name: Verify AWS CLI version
      command: aws --version
      changed_when: false
